
type MENU_LIST_TYPE = {
    item: string
    state: boolean
    price: number
}[]

const MENU_LIST: MENU_LIST_TYPE = [
    { item: "Afang Soup", price: 2000, state: false },
    { item: "Amala", price: 2000, state: false },
    { item: "Atama Soup", price: 2000, state: false },
    { item: "Banga Soup", price: 2000, state: false },
    { item: "Bitter Leaf Soup", price: 2000, state: false },
    { item: "Editang Soup", price: 2000, state: false },
    { item: "Egusi Soup", price: 2000, state: false },
    { item: "Native Soup", price: 4500, state: false },
    { item: "Oha Soup", price: 2000, state: false },
    { item: "Pepper Soup", price: 1000, state: false },
    { item: "Seafood Okra Soup", price: 4500, state: false },
    { item: "White Soup", price: 2000, state: false },
    { item: "Garri", price: 500, state: false },
    { item: "Fufu", price: 500, state: false },
    { item: "Pounded Yam", price: 1000, state: false },
    { item: "Semovita", price: 1000, state: false },
    { item: "Chicken Wings Sauce", price: 5000, state: false },
    { item: "Chinese Fried Rice", price: 5000, state: false },
    { item: "Coconut Rice", price: 3000, state: false },
    { item: "Continental Fried Rice", price: 3000, state: false },
    { item: "Jambalaya Rice", price: 5000, state: false },
    { item: "Jellof Noodles", price: 2000, state: false },
    { item: "Nigerian Jollof Rice", price: 3000, state: false },
    { item: "Ofada Rice", price: 3000, state: false },
    { item: "Pomodoro Spaghetti", price: 3500, state: false },
    { item: "Prime Pork Sauce", price: 5000, state: false },
    { item: "Salad", price: 500, state: false },
    { item: "TKmotive Native Rice", price: 3000, state: false },
    { item: "TKmotive Premium Sauce", price: 6000, state: false },
    { item: "Unpolished White Rice & Veg", price: 2000, state: false },
    { item: "Boiled Vegetable Beans", price: 1500, state: false },
    { item: "Moi-moi", price: 1000, state: false },
    { item: "Porridge Beans", price: 1500, state: false },
    { item: "Chipped Potato with 3 Egg Wrapped", price: 3500, state: false },
    { item: "Chipped Potato & TKmotive Sauce", price: 6000, state: false },
    { item: "Chipped Yam with 3 Egg Wrapped", price: 3500, state: false },
    { item: "Chipped Yam & TKmotive Sauce", price: 6000, state: false },
    { item: "Yam Vegetable Porridge", price: 4500, state: false },
    { item: "Onunu & Fish Peppe Soup or Sauce", price: 10000, state: false },
    { item: "Boiled Plantain & TKmotive Sauce", price: 6000, state: false },
    { item: "Fried Plantain", price: 500, state: false },
    { item: "Gizzdodo including Liver & Veg", price: 5000, state: false },
    { item: "Plantain Vegetable Porridge", price: 4500, state: false },
    { item: "Assorted / Cow Head / Goat/ Gizzard", price: 2000, state: false },
    { item: "Ferry Snail", price: 5500, state: false },
    { item: "Fried Egg (2) with added Veg", price: 2000, state: false },
    { item: "Fried Fish (Red Snapper)", price: 4500, state: false },
    { item: "Pepped Beef", price: 1000, state: false },
    { item: "Pepped Chicken", price: 2500, state: false },
    { item: "Pepped Crocker Fish", price: 3500, state: false },
    { item: "Pepped Goat Meat", price: 2500, state: false },
    { item: "Prime King Prawns", price: 5000, state: false },
    { item: "Grilled Chicken Wings", price: 5500, state: false },
    { item: "Doughnut / Pancakes", price: 1000, state: false },
    { item: "Fish Roll / Chicken Rolls / Scotch Egg", price: 1000, state: false },
    { item: "Shawarma (Chicken with 2 Sausage)", price: 2500, state: false },
    { item: "Grilled Chicken", price: 2500, state: false },
    { item: "Grilled Fish (Catfish / Crocker)", price: 4000, state: false },
    { item: "Samosa / Puff Puff / Chicken Pie", price: 1000, state: false }
  ];
  

export default MENU_LIST